FROM python:3.9-buster

# 環境変数の設定
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS=yes

WORKDIR /app

COPY requirements.txt .    
COPY index_data.py .    

# 必要なパッケージのインストール
RUN apt-get update && \
    apt-get install -y apt-utils apt-transport-https gnupg curl && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools unixodbc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Pythonパッケージのインストール
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

CMD ["python", "/app/index_data.py"]