services:  
  indexer:  
    build:  
      context: .  
      dockerfile: Dockerfile  
    platform: linux/amd64  
    env_file:  
      - .env  
    volumes:  
      - .:/app  
    deploy:  
      resources:  
        limits:  
          memory: 4G  
        reservations:  
          memory: 2G  
    stdin_open: true  
    tty: true  